USUARIO = 'SELECT * FROM USUARIO;'

PRIVILEGIO = 'SELECT * FROM PRIVILEGIO;'

TRANSACAO = 'SELECT * FROM TRANSACAO;'

MURAL = 'SELECT * FROM MURAL;'

CHAMADO = 'SELECT * FROM CHAMADO'

SALDO_TOTAL = 'SELECT SUM(SALDO) FROM TRANSACAO AS SALDO_TOTAL'