from src.user import User

class Membro(User):
    def __init__(self, n_matricula:str, nome:str, senha:str, email:str, cargo:str):
        super().__init__(n_matricula, nome, senha, email)
        self.cargo = cargo
    
    def cadastrar_usuario(self, usuario:User): ...

    def editar_usuario(self, n_matricula:str): ...

    def excluir_usuario(self, n_matricula:str): ...

    def criar_aviso(self): ...

    def editar_aviso(self): ...

    def excluir_aviso(self): ...

    def criar_relatorio_financeiro(self): ...

    def editar_relatorio_financeiro(self): ...

    def excluir_relatorio_financeiro(self): ...

    def publicar_relatorio_financeiro(self): ...

    def editar_chamado(self): ...